feat: добавить бронирование вещей
a-mihalych/java-shareit pull request #2
Opened 2023-02-09 20:45 UTC by a-mihalych

2023-02-10 20:18 UTC, ohelly requested changes
Привет! Отличная работа, в целом все корректно работает. Есть пара простых замечаний, а также ряд рекомендаций, на которые стоит обратить внимание.

Возможно мои замечания не будут коррелировать с тестами постмана, в таком случае оставляй как есть.

2023-02-10 20:18 UTC, ohelly commented on pom.xml
>  		<dependency>
Рекомендация: зависимость на h2 больше не нужна, можно вырезать

2023-02-10 20:18 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
Рекомендация: Обычно сервис инжектит в себя только "свой" репозиторий(в данном случае ItemRepository), а ко всем остальным доступ через их сервисы. Сервис является точкой входа в репозиторий и в них реализована бизнес логика, которая может меняться. Если все будут использовать сервис то при изменении логики в нем она применится ко всем, кто ее использует, но при использовании репозитория такое не произойдет, потому что бизнес логику в нем не пишут, он обычно только достает какие то данные

2023-02-10 20:18 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +public class BookingMapper {
Рекомендация: Рекомендую почитать про такую штуку как mupstruct. Очень сильно поможет сэкономить время при написании мапперов для дтошек.

2023-02-10 20:18 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("Обновление прервано, вещь другого пользователя");
Необходимо исправить: В случае, когда человек пытается изменить статус не своей вещи выкидывается NotFoundException, что по сути неверно. Для этого можно создать ForbiddenException и в хендлере выкидывать соответствующий 403 статус.

Аналогично с методом bookingById

2023-02-10 20:18 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> {
Рекомендация: Будет лучше преобразовать входящую строку state в enum:
``StatusBooking statusBooking = StatusBooking.valueOf(state);``
И уже его использовать внутри оператора switch. Данный подходит сократит вероятность опечатки, а также если enum'ы поменяют свое название, то здесь ничего менять не придется.

2023-02-12 14:22 UTC, a-mihalych commented on pom.xml
>  		<dependency>
Попробовал удалить, без этой зависимости не запускается. Как я понимаю, тесты с h2 работают.

2023-02-12 14:26 UTC, a-mihalych commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("Обновление прервано, вещь другого пользователя");
У меня такая ошибка есть (ForbiddenOperationException), но тест в этом месте проверяет на 404.

2023-02-12 14:42 UTC, a-mihalych commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +public class BookingMapper {
Да, я ещё на прошлом спринте почитал про mupstruct, но использовать не решился. А в этом спринте, у нас в группе уже несколько дискуссий было, многие не в "восторге" от него. Учитывая, что я отстаю от графика, лучше, наверное, сейчас мне сильно не экспериментировать. Но спасибо, я запомнил, попробую потом на своём проекте его использовать.

2023-02-12 19:52 UTC, a-mihalych commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> {
Сделал

2023-02-13 03:28 UTC, a-mihalych commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
Сделал

2023-02-13 18:13 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("Обновление прервано, вещь другого пользователя");
странные тесты конечно)

2023-02-13 18:14 UTC, ohelly approved these changes
Привет! Все супер, все работает корректно. Работу принимаю, удачи в дальнейшем обучении!

2023-02-14 21:09 UTC, merged